export const spanishKeysUsers = {
    user_id: "ID de usuario",
    name: "Nombre",
    first_last_name: "Apellido paterno",
    second_last_name: "Apellido materno",
    date_of_birth: "Fecha de nacimiento",
    nationality: "Nacionalidad",
    state_of_birth: "Estado de nacimiento",
    economic_activity: "Actividad económica",
    curp: "CURP",
    gender: "Género",
    phone_number: "Número de teléfono",
    email: "Email",
    is_client: "Es Cliente",
    is_blocked: "Está Bloqueado",
    created_at: "Fecha de creación",
    updated_at: "Fecha de actualización",
    deleted_at: "Fecha de eliminación",
    rfc: "RFC"
}
export const spanishKeysAddresses = {
    address_id: "ID de dirección",
    country:  "País",
    state: "Estado",
    city: "Ciudad",
    neighborhood: "Colonia",
    zip_code: "Código postal",
    street: "Calle",
    ext_number: "Número exterior",
    int_number: "Número interior",
    created_at: "Fecha de creación",
    updated_at: "Fecha de actualización",
    deleted_at: "Fecha de eliminación",
}
export const spanishKeysIdentifications = {
    identification_id: "ID de identificación",
    identification_type: "Tipo de identificación",
    identification_number: "Número de identificación",
    created_at: "Fecha de creación",
    updated_at: "Fecha de actualización",
    deleted_at: "Fecha de eliminación",
}